import "./globals.css";
import { Inter } from "next/font/google";
import VerticalNavbar from "@/components/VerticalNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`border-box  ${inter.className} max-w-5xl  mx-auto  `}
            >
                <div className="flex min-h-screen p-5">
                    <VerticalNavbar />
                    <main className=" flex-grow p-4 bg-blue-50 rounded-r-xl">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
